export const CREATE_SCAN_SESSION = 'CREATE_SCANNING_SESSION';
export const EDIT_SCAN_SESSION = 'EDIT_SCANNING_SESSION';
export const ADD_BOOK_TO_SCAN_SESSION = 'ADD_BOOK_TO_SESSION';
export const EDIT_BOOK_TO_SCAN_SESSION = 'EDIT_BOOK_TO_SESSION';
export const SYNC_SCANNING_SESSIONS = 'SYNC_SCANNING_SESSIONS';
export const DELETE_SESSION = 'DELETE_SESSION';
export const DELETE_BOOK = 'DELETE_BOOK';
